app1/urls.py
from django.urls import path
from app1.views import app1_specific
app_name='app1'
urlpatterns=[path('app1_specific/',app1_specific,name='app1_specific'),]

project11/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from app.views import hai,bye
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('bye/',bye,name='bye'),
    path('app1/',include('app1.urls'))
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

def bye(request):
    return render(request,'bye.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def app1_specific(request):
    return render(request,'specific.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Bye html page</h1>
        <h2><a href="{% url 'hai' %}">Navigate to HAI</a></h2>
        <h2><a href="{% url 'app1:app1_specific' %}">Naviagate tos app1_specific</a></h2>
    </center>
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Hai html page</h1>
        <h2><a href="{% url 'bye' %}">Navigate to BYE</a></h2>
        <h2><a href="{% url 'app1:app1_specific' %}">Naviagate to app1_specific</a></h2>
    </center>
</body>
</html>

templates/specific.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to  app1_specific</h1>
        <h2><a href="{% url 'hai' %}">naviagate to hai</a></h2>
        <h2><a href="{% url 'bye' %}">Naviagate to Bye</a></h2>
    </center>
</body>
</html>